# medicines_pakistan.py
# Pakistan-specific medicine database
# Sources: DRAP (Drug Regulatory Authority Pakistan), Pakistan NF, local pharmacy data
# Note: Always consult a licensed pharmacist or doctor before use.

MEDICINES_PAKISTAN = {
    "acne": [
        {
            "generic": "Benzoyl Peroxide 5%",
            "brands_pk": ["Oxy-5", "Benzac AC", "PanOxyl"],
            "type": "Topical Cream/Gel",
            "usage_en": "Apply a thin layer to affected area once daily. Start with every other day to reduce irritation.",
            "usage_ur": "متاثرہ جگہ پر پتلی تہہ لگائیں۔ شروع میں ایک دن چھوڑ کر لگائیں۔",
            "price_pkr": "180–350",
            "rx_required": False,
            "caution_en": "May bleach hair and fabric. Avoid eyes and mucous membranes.",
            "caution_ur": "بالوں اور کپڑوں کو رنگ اڑا سکتا ہے۔ آنکھوں سے دور رکھیں۔",
        },
        {
            "generic": "Clindamycin 1% Solution/Gel",
            "brands_pk": ["Dalacin T", "Clindac A", "Clinda-Gel"],
            "type": "Topical Antibiotic",
            "usage_en": "Apply to affected area twice daily (morning and evening).",
            "usage_ur": "دن میں دو بار (صبح و شام) متاثرہ جگہ پر لگائیں۔",
            "price_pkr": "250–500",
            "rx_required": True,
            "caution_en": "Do not use for more than 12 weeks to avoid antibiotic resistance.",
            "caution_ur": "اینٹی بائیوٹک مزاحمت سے بچنے کے لیے 12 ہفتوں سے زیادہ استعمال نہ کریں۔",
        },
        {
            "generic": "Tretinoin 0.025–0.05% Cream",
            "brands_pk": ["Retin-A", "Aberela", "Airol"],
            "type": "Topical Retinoid",
            "usage_en": "Apply pea-sized amount at bedtime. Use sunscreen daily. Avoid in pregnancy.",
            "usage_ur": "رات کو مٹر کے دانے جتنی مقدار لگائیں۔ دھوپ سے بچاؤ ضروری ہے۔ حمل میں استعمال نہ کریں۔",
            "price_pkr": "300–700",
            "rx_required": True,
            "caution_en": "CONTRAINDICATED in pregnancy. May cause initial purging and photosensitivity.",
            "caution_ur": "حمل میں بالکل ممنوع ہے۔ شروع میں دانے بڑھ سکتے ہیں — یہ عارضی ہے۔",
        },
        {
            "generic": "Salicylic Acid 2% Face Wash",
            "brands_pk": ["Neutrogena SA", "Clean & Clear SA", "Acnecide Wash"],
            "type": "OTC Cleanser",
            "usage_en": "Use as face wash twice daily. Helps unclog pores.",
            "usage_ur": "دن میں دو بار چہرہ دھونے کے لیے استعمال کریں۔ مساموں کو صاف کرتا ہے۔",
            "price_pkr": "400–900",
            "rx_required": False,
            "caution_en": "Avoid around eyes. May cause dryness — use moisturizer.",
            "caution_ur": "آنکھوں کے قریب نہ لگائیں۔ خشکی ہو تو موئسچرائزر استعمال کریں۔",
        },
    ],

    "eczema": [
        {
            "generic": "Hydrocortisone 1% Cream",
            "brands_pk": ["Hydrocort", "Cortaid", "Euzone"],
            "type": "Mild Topical Corticosteroid",
            "usage_en": "Apply thin layer to affected area 2–3 times daily. For mild eczema and face use.",
            "usage_ur": "متاثرہ جگہ پر دن میں 2–3 بار پتلی تہہ لگائیں۔ چہرے کے لیے موزوں ہے۔",
            "price_pkr": "80–200",
            "rx_required": False,
            "caution_en": "Do not use on face for more than 7 days. Avoid broken skin.",
            "caution_ur": "چہرے پر 7 دن سے زیادہ استعمال نہ کریں۔ کٹی جلد پر نہ لگائیں۔",
        },
        {
            "generic": "Betamethasone 0.1% Cream",
            "brands_pk": ["Betnovate", "Dermovate 0.05%", "Celestoderm"],
            "type": "Moderate-Potent Topical Corticosteroid",
            "usage_en": "Apply once or twice daily to severely affected areas (not face/skin folds). Short-term use only.",
            "usage_ur": "شدید متاثرہ جگہوں پر دن میں ایک یا دو بار لگائیں۔ چہرے اور سلوٹوں پر نہ لگائیں۔",
            "price_pkr": "120–300",
            "rx_required": True,
            "caution_en": "Strong steroid — use minimum duration. Risk of skin thinning with prolonged use.",
            "caution_ur": "طاقتور دوا — کم سے کم وقت تک استعمال کریں۔ لمبے عرصے تک جلد پتلی ہو سکتی ہے۔",
        },
        {
            "generic": "Tacrolimus 0.03% / 0.1% Ointment",
            "brands_pk": ["Protopic", "Tacrobell"],
            "type": "Topical Calcineurin Inhibitor",
            "usage_en": "Apply twice daily. For long-term management. Preferred for face and sensitive areas.",
            "usage_ur": "دن میں دو بار لگائیں۔ چہرے اور حساس جگہوں کے لیے بہترین۔",
            "price_pkr": "800–2000",
            "rx_required": True,
            "caution_en": "Avoid prolonged sun exposure. Burning sensation may occur initially.",
            "caution_ur": "دھوپ سے بچیں۔ شروع میں جلن ہو سکتی ہے — عام بات ہے۔",
        },
        {
            "generic": "Moisturising Emollient (Urea 10% or Paraffin-based)",
            "brands_pk": ["Eucerin Urea", "E45 Cream", "Vanicream", "Diprobase"],
            "type": "Emollient / Moisturiser",
            "usage_en": "Apply generously 2–3 times daily to all dry skin areas. Cornerstone of eczema management.",
            "usage_ur": "دن میں 2–3 بار تمام خشک جگہوں پر خوب لگائیں۔ یہ علاج کی بنیاد ہے۔",
            "price_pkr": "500–1500",
            "rx_required": False,
            "caution_en": "Use immediately after bathing. Safe for long-term daily use.",
            "caution_ur": "نہانے کے فوری بعد لگائیں۔ روزانہ طویل عرصے تک استعمال کیا جا سکتا ہے۔",
        },
    ],

    "psoriasis": [
        {
            "generic": "Calcipotriol 0.005% Cream/Ointment",
            "brands_pk": ["Daivonex", "Calcimax", "Dovonex"],
            "type": "Topical Vitamin D Analogue",
            "usage_en": "Apply to plaques twice daily. Max 100g per week. Avoid face and flexures.",
            "usage_ur": "دانوں پر دن میں دو بار لگائیں۔ چہرے اور سلوٹوں پر استعمال نہ کریں۔",
            "price_pkr": "600–1200",
            "rx_required": True,
            "caution_en": "Do not exceed weekly dose. May irritate face and skin folds.",
            "caution_ur": "ہفتہ وار مقدار سے زیادہ نہ لگائیں۔ چہرے پر جلن ہو سکتی ہے۔",
        },
        {
            "generic": "Calcipotriol + Betamethasone Dipropionate Gel",
            "brands_pk": ["Daivobet", "Enstilar Foam", "Xamiol"],
            "type": "Combination Topical Therapy",
            "usage_en": "Apply once daily for up to 4 weeks. Most effective psoriasis topical treatment.",
            "usage_ur": "4 ہفتوں تک روزانہ ایک بار لگائیں۔ صدف کے لیے سب سے مؤثر مقامی علاج۔",
            "price_pkr": "1200–2500",
            "rx_required": True,
            "caution_en": "Potent steroid risk with prolonged use. Short-term use recommended.",
            "caution_ur": "لمبے عرصے میں اسٹیرائیڈ کا خطرہ۔ مختصر مدت کے لیے استعمال کریں۔",
        },
        {
            "generic": "Coal Tar 5–10% Solution/Shampoo",
            "brands_pk": ["Polytar", "T/Gel", "Ionil T", "Coal Tar BP"],
            "type": "Topical Tar Preparation",
            "usage_en": "Apply to plaques or use as shampoo. Leave for 5–10 minutes then rinse.",
            "usage_ur": "دانوں پر لگائیں یا شیمپو کے طور پر استعمال کریں۔ 5–10 منٹ چھوڑ کر دھو لیں۔",
            "price_pkr": "200–600",
            "rx_required": False,
            "caution_en": "Strong odour. May stain clothing and skin. Avoid eyes.",
            "caution_ur": "تیز بو ہے۔ کپڑے اور جلد داغدار ہو سکتے ہیں۔ آنکھوں سے دور رکھیں۔",
        },
    ],

    "fungal_infection": [
        {
            "generic": "Clotrimazole 1% Cream",
            "brands_pk": ["Canesten", "Mycoten", "Fungistop", "Clotri"],
            "type": "Topical Antifungal",
            "usage_en": "Apply to affected area and 2cm around it, twice daily for 2–4 weeks.",
            "usage_ur": "متاثرہ جگہ اور اس کے 2 سینٹی میٹر ارد گرد دن میں دو بار 2–4 ہفتے لگائیں۔",
            "price_pkr": "100–300",
            "rx_required": False,
            "caution_en": "Complete full course even if symptoms improve to prevent recurrence.",
            "caution_ur": "لکشات ٹھیک ہونے پر بھی پورا کورس مکمل کریں تاکہ دوبارہ نہ ہو۔",
        },
        {
            "generic": "Terbinafine 1% Cream / 250mg Tablets",
            "brands_pk": ["Lamisil", "Terbicil", "Terbin", "Funginix"],
            "type": "Allylamine Antifungal",
            "usage_en": "Cream: Apply once daily for 1–2 weeks. Tablets (for nail/scalp): 250mg once daily for 6–12 weeks.",
            "usage_ur": "کریم: 1–2 ہفتے روزانہ ایک بار لگائیں۔ گولیاں (ناخن/سر کے لیے): روزانہ ایک 250mg گولی۔",
            "price_pkr": "Cream 150–400 / Tablets 800–1500",
            "rx_required": True,
            "caution_en": "Tablets require liver function monitoring. Inform doctor of all medications.",
            "caution_ur": "گولیوں کے ساتھ جگر کا معائنہ ضروری ہے۔ ڈاکٹر کو تمام دوائیں بتائیں۔",
        },
        {
            "generic": "Fluconazole 150mg Capsule",
            "brands_pk": ["Diflucan", "Fluzole", "Flucon", "Trianzol"],
            "type": "Systemic Antifungal",
            "usage_en": "Single dose 150mg for superficial fungal infections. Doctor-prescribed regimen for severe cases.",
            "usage_ur": "عام فنگل انفیکشن کے لیے ایک 150mg کیپسول کافی۔ شدید کیسز میں ڈاکٹر کا نسخہ لیں۔",
            "price_pkr": "150–400",
            "rx_required": True,
            "caution_en": "Many drug interactions. Avoid in pregnancy (first trimester). Doctor consultation required.",
            "caution_ur": "دوسری دوائیوں کے ساتھ تعامل ہو سکتا ہے۔ حمل کے پہلے 3 مہینوں میں نہ لیں۔",
        },
    ],

    "scabies": [
        {
            "generic": "Permethrin 5% Cream",
            "brands_pk": ["Scabisan", "Pemix", "Elimite", "Nix"],
            "type": "Topical Scabicide",
            "usage_en": "Apply from neck to toes at night. Wash off after 8–12 hours. Repeat after 1 week. Treat all household members simultaneously.",
            "usage_ur": "رات کو گردن سے پاؤں تک لگائیں۔ 8–12 گھنٹے بعد دھو لیں۔ 1 ہفتے بعد دوبارہ لگائیں۔ گھر کے سب کا علاج ایک ساتھ کریں۔",
            "price_pkr": "200–500",
            "rx_required": True,
            "caution_en": "Preferred treatment in Pakistan. Safe in adults and children > 2 months.",
            "caution_ur": "پاکستان میں پسندیدہ علاج۔ بالغوں اور 2 ماہ سے بڑے بچوں کے لیے محفوظ۔",
        },
        {
            "generic": "Benzyl Benzoate 25% Lotion",
            "brands_pk": ["Ascabiol", "Scabex", "Benzemul"],
            "type": "Topical Scabicide",
            "usage_en": "Apply to whole body below neck. Leave overnight. Wash off. Dilute to 12.5% for children.",
            "usage_ur": "پورے جسم پر (گردن سے نیچے) لگائیں۔ رات بھر چھوڑیں۔ بچوں کے لیے پانی سے آدھا کریں۔",
            "price_pkr": "80–200",
            "rx_required": False,
            "caution_en": "Can irritate skin. Dilute for children and elderly. Avoid eyes and mouth.",
            "caution_ur": "جلد میں جلن ہو سکتی ہے۔ بچوں اور بزرگوں کے لیے پتلا کریں۔ آنکھوں سے دور رکھیں۔",
        },
        {
            "generic": "Ivermectin 3mg Tablets (Oral)",
            "brands_pk": ["Ivectin", "Scabo", "Ivermec"],
            "type": "Oral Antiparasitic",
            "usage_en": "200mcg/kg as single oral dose. Repeat after 2 weeks. Used in crusted scabies or treatment failure.",
            "usage_ur": "جسمانی وزن کے مطابق ایک خوراک منہ سے لیں۔ 2 ہفتے بعد دوبارہ۔ شدید خارش میں استعمال۔",
            "price_pkr": "100–300",
            "rx_required": True,
            "caution_en": "Not for children < 15kg or pregnancy. Prescription required.",
            "caution_ur": "15 کلو سے کم وزن کے بچوں اور حاملہ خواتین کے لیے نہیں۔ نسخہ ضروری ہے۔",
        },
    ],

    "vitiligo": [
        {
            "generic": "Tacrolimus 0.1% Ointment",
            "brands_pk": ["Protopic", "Tacrobell"],
            "type": "Topical Calcineurin Inhibitor",
            "usage_en": "Apply twice daily to depigmented patches, especially on face. Can be used long-term.",
            "usage_ur": "سفید دھبوں پر دن میں دو بار لگائیں، خاص کر چہرے پر۔ طویل مدت استعمال ممکن ہے۔",
            "price_pkr": "800–2000",
            "rx_required": True,
            "caution_en": "Avoid sun exposure during treatment. Most effective on face and neck patches.",
            "caution_ur": "علاج کے دوران دھوپ سے بچیں۔ چہرے اور گردن کے دھبوں پر سب سے زیادہ مؤثر۔",
        },
        {
            "generic": "Narrowband UVB Therapy",
            "brands_pk": ["Available at dermatology clinics"],
            "type": "Phototherapy",
            "usage_en": "2–3 sessions per week at a dermatology clinic. Takes 6+ months for visible results.",
            "usage_ur": "ہفتے میں 2–3 بار ماہر جلد کے کلینک میں جائیں۔ نتائج 6+ مہینوں میں نظر آتے ہیں۔",
            "price_pkr": "500–2000 per session",
            "rx_required": True,
            "caution_en": "Gold standard treatment. Requires consistent attendance. Use sunscreen on treated skin.",
            "caution_ur": "بہترین علاج۔ باقاعدگی ضروری ہے۔ علاج کے بعد سن اسکرین لگائیں۔",
        },
    ],

    "contact_dermatitis": [
        {
            "generic": "Hydrocortisone 1% Cream",
            "brands_pk": ["Hydrocort", "Cortaid", "Euzone"],
            "type": "Mild Topical Corticosteroid",
            "usage_en": "Apply 2–3 times daily to inflamed area. Remove the causative agent first.",
            "usage_ur": "سوجن والی جگہ پر دن میں 2–3 بار لگائیں۔ پہلے وجہ دور کریں۔",
            "price_pkr": "80–200",
            "rx_required": False,
            "caution_en": "Identify and avoid the trigger. Most important step.",
            "caution_ur": "سب سے پہلے وجہ معلوم کریں اور اس سے بچیں۔",
        },
        {
            "generic": "Chlorphenamine (Chlorpheniramine) 4mg Tablet",
            "brands_pk": ["Piriton", "Chlor-Trimeton", "Allergex"],
            "type": "Oral Antihistamine (Sedating)",
            "usage_en": "4mg 3–4 times daily for itching. Causes drowsiness — avoid driving.",
            "usage_ur": "خارش کے لیے دن میں 3–4 بار 4mg لیں۔ نیند آتی ہے — گاڑی نہ چلائیں۔",
            "price_pkr": "20–80",
            "rx_required": False,
            "caution_en": "Avoid alcohol. May impair alertness.",
            "caution_ur": "شراب سے پرہیز کریں۔ دھیان کم ہو سکتا ہے۔",
        },
    ],

    "urticaria": [
        {
            "generic": "Cetirizine 10mg Tablet",
            "brands_pk": ["Zirtec", "Rigix", "Cetrin", "Incidal OD"],
            "type": "Non-Sedating Oral Antihistamine",
            "usage_en": "10mg once daily (at night to minimise drowsiness). For acute and chronic urticaria.",
            "usage_ur": "10mg روزانہ رات کو لیں۔ دائمی اور فوری چھپاکی دونوں کے لیے مؤثر۔",
            "price_pkr": "60–200",
            "rx_required": False,
            "caution_en": "May cause mild drowsiness. Safe for long-term use in chronic urticaria.",
            "caution_ur": "ہلکی نیند آ سکتی ہے۔ دائمی چھپاکی میں طویل مدت استعمال محفوظ ہے۔",
        },
        {
            "generic": "Loratadine 10mg Tablet",
            "brands_pk": ["Clarityne", "Roletra", "Lorfast", "Claritin"],
            "type": "Non-Sedating Oral Antihistamine",
            "usage_en": "10mg once daily. Non-drowsy formula suitable for daytime use.",
            "usage_ur": "روزانہ 10mg ایک بار لیں۔ نیند نہیں آتی — دن میں استعمال کے لیے موزوں۔",
            "price_pkr": "80–250",
            "rx_required": False,
            "caution_en": "Preferred for patients needing to remain alert. Take on empty stomach.",
            "caution_ur": "ڈرائیوروں اور طلباء کے لیے موزوں۔ خالی پیٹ لیں۔",
        },
        {
            "generic": "Prednisolone 5–40mg (Short course)",
            "brands_pk": ["Pred", "Predsolone", "Decortin", "Omnacortil"],
            "type": "Oral Corticosteroid (short course only)",
            "usage_en": "Doctor-prescribed short course (5–7 days) for severe acute urticaria. NOT for chronic use.",
            "usage_ur": "شدید چھپاکی میں ڈاکٹر کے نسخے پر 5–7 دن کا کورس۔ دائمی استعمال ممنوع۔",
            "price_pkr": "30–150",
            "rx_required": True,
            "caution_en": "Short-course only. Many side effects with prolonged use. Doctor supervision essential.",
            "caution_ur": "صرف مختصر کورس۔ لمبے عرصے میں شدید نقصان۔ ڈاکٹر کی نگرانی ضروری ہے۔",
        },
    ],

    "rosacea": [
        {
            "generic": "Metronidazole 0.75% Gel",
            "brands_pk": ["Rozex", "Metro Gel", "Flagyl Gel", "Metrogel"],
            "type": "Topical Antibacterial/Antiprotozoal",
            "usage_en": "Apply twice daily to affected facial areas. For papulopustular rosacea.",
            "usage_ur": "چہرے کی متاثرہ جگہ پر دن میں دو بار لگائیں۔ دانے والے روزاسیا کے لیے۔",
            "price_pkr": "300–700",
            "rx_required": True,
            "caution_en": "Avoid sun exposure. Use gentle, fragrance-free skincare.",
            "caution_ur": "دھوپ سے بچیں۔ خوشبو سے پاک کاسمیٹکس استعمال کریں۔",
        },
        {
            "generic": "Azelaic Acid 15% Gel / 20% Cream",
            "brands_pk": ["Skinoren", "Aziderm", "Finacea"],
            "type": "Topical Anti-inflammatory",
            "usage_en": "Apply twice daily. Reduces redness and bumps. Also helps with post-acne marks.",
            "usage_ur": "دن میں دو بار لگائیں۔ سرخی اور دانے کم کرتا ہے۔ مہاسوں کے داغ بھی مٹاتا ہے۔",
            "price_pkr": "400–1000",
            "rx_required": True,
            "caution_en": "May cause initial tingling. Safe in pregnancy.",
            "caution_ur": "شروع میں چبھن ہو سکتی ہے — عام بات ہے۔ حمل میں محفوظ ہے۔",
        },
    ],

    "melanoma": [
        {
            "generic": "⚠️ URGENT REFERRAL REQUIRED",
            "brands_pk": ["Not a condition for OTC treatment"],
            "type": "Medical Emergency",
            "usage_en": "Melanoma MUST be treated by an oncologist/dermatologist. Do not attempt self-treatment. Surgical excision is the primary treatment.",
            "usage_ur": "میلانوما کا علاج صرف ماہر سرطان یا ماہر جلد کر سکتے ہیں۔ خود علاج بالکل نہ کریں۔ سرجری بنیادی علاج ہے۔",
            "price_pkr": "Varies — specialist consultation required",
            "rx_required": True,
            "caution_en": "CRITICAL: Time is essential. Book specialist appointment TODAY. Pakistan has oncology centres in Karachi (Aga Khan, SKMCH), Lahore (SKMCH), and Islamabad.",
            "caution_ur": "نازک: وقت بہت اہم ہے۔ آج ہی ماہر سے ملیں۔ پاکستان میں SKMCH لاہور، آغا خان کراچی، اور اسلام آباد میں ماہرین موجود ہیں۔",
        },
    ],
}


CARE_TIPS = {
    "acne": [
        "Wash face gently twice daily with a mild, non-comedogenic cleanser",
        "Avoid picking or squeezing pimples — causes scarring",
        "Use oil-free, non-comedogenic moisturiser and sunscreen",
        "Change pillowcases twice a week",
        "Diet: reduce dairy, sugary foods, and high-glycemic index foods",
        "Manage stress — it triggers hormonal acne",
        "جلد صاف رکھیں مگر بار بار نہ دھوئیں",
        "مہاسوں کو نہ چھیڑیں — داغ پڑتے ہیں",
    ],
    "eczema": [
        "Moisturise immediately after every bath — within 3 minutes (wet dressing technique)",
        "Use lukewarm water (not hot) for bathing, limit to 10 minutes",
        "Wear soft cotton clothing — avoid wool and synthetic fabrics",
        "Use fragrance-free, dye-free laundry detergent",
        "Identify and avoid personal triggers (dust, pet, food)",
        "Keep nails short to minimise skin damage from scratching",
        "نہانے کے فوری بعد موئسچرائزر لگائیں",
        "نرم سوتی کپڑے پہنیں",
    ],
    "psoriasis": [
        "Moisturise daily to reduce scaling and itching",
        "Expose to moderate sunlight (10–15 min daily) — helps many patients",
        "Avoid stress — major trigger",
        "Quit smoking and limit alcohol consumption",
        "Be gentle with skin — avoid scratching or picking plaques",
        "Keep flares diary to identify personal triggers",
        "باقاعدگی سے موئسچرائزر لگائیں",
        "تناؤ سے بچیں — علاج میں مدد ملتی ہے",
    ],
    "fungal_infection": [
        "Keep affected area clean and DRY — fungi thrive in moisture",
        "Wear breathable cotton underwear and socks",
        "Change socks daily; wear sandals in public showers/pools",
        "Do NOT share towels, combs, or footwear",
        "Complete full course of antifungal — even after improvement",
        "Treat all affected household members and pets",
        "متاثرہ جگہ خشک رکھیں",
        "تولیہ اور جوتے شیئر نہ کریں",
    ],
    "scabies": [
        "Wash ALL clothing, bedding, and towels in hot water (>60°C) on treatment day",
        "Items that cannot be washed — seal in plastic bag for 3–4 days",
        "Vacuum carpets and upholstered furniture thoroughly",
        "Treat ALL household and close contacts simultaneously",
        "Itching may persist 2–4 weeks after successful treatment — normal",
        "Avoid close physical contact with others until treatment is complete",
        "علاج کے دن تمام کپڑے اور بستر گرم پانی میں دھوئیں",
        "گھر کے تمام افراد کا ایک ساتھ علاج کریں",
    ],
    "vitiligo": [
        "Apply broad-spectrum SPF 50+ sunscreen on patches daily",
        "Wear protective clothing and seek shade — patches burn easily",
        "Consider camouflage cosmetics for psychological wellbeing",
        "Join a support group — vitiligo is not contagious and not dangerous",
        "Maintain healthy diet rich in antioxidants (Vitamin C, E, beta-carotene)",
        "سفید دھبوں پر سن اسکرین ضرور لگائیں",
        "یاد رکھیں — برص چھوت کی بیماری نہیں ہے",
    ],
    "contact_dermatitis": [
        "FIRST: Identify and completely avoid the trigger",
        "If trigger is a chemical — wash the area immediately with soap and water",
        "For jewellery-related: switch to surgical steel, titanium, or gold",
        "Use fragrance-free, hypoallergenic skin products",
        "Patch test new products on inner arm before facial use",
        "پہلے وجہ معلوم کریں اور اس سے بچیں",
        "نئی مصنوعات پہلے کلائی پر آزمائیں",
    ],
    "urticaria": [
        "Keep a diary of foods, medications, and activities before each episode",
        "Avoid identified triggers (certain foods, NSAIDs, stress, extreme temperatures)",
        "Wear loose, cool clothing; avoid tight waistbands (pressure urticaria)",
        "Cool shower or cold compress relieves itching temporarily",
        "Do NOT take aspirin or ibuprofen — common trigger",
        "کھانے اور ادویات کی ڈائری رکھیں",
        "اسپرین اور brufen سے پرہیز کریں",
    ],
    "rosacea": [
        "Identify and strictly avoid personal triggers (keep a diary)",
        "Use broad-spectrum SPF 30+ sunscreen DAILY",
        "Avoid hot drinks, spicy food, and alcohol",
        "Use gentle, fragrance-free, rosacea-safe skincare only",
        "Protect face from wind and extreme cold",
        "وجوہات کی ڈائری رکھیں اور ان سے بچیں",
        "روزانہ سن اسکرین لگائیں",
    ],
    "melanoma": [
        "URGENT: Book appointment with dermatologist/oncologist TODAY",
        "Take photos to document any changes in the lesion",
        "Do NOT attempt to remove the mole yourself",
        "Protect all skin from UV exposure (SPF 50+, protective clothing)",
        "Check all other moles using the ABCDE rule monthly",
        "فوری: آج ہی ماہر سے ملاقات کا وقت لیں",
        "کسی بھی تل کو خود نہ ہٹائیں",
    ],
}


def get_medicines(condition_key):
    """Return medicine list for a given condition."""
    return MEDICINES_PAKISTAN.get(condition_key, [])


def get_care_tips(condition_key):
    """Return care tips for a given condition."""
    return CARE_TIPS.get(condition_key, [])
